### ISSUE TITLE
can't seem add or view data from database

### ISSUE THREAD

**Issue by kwaknet01** [TheWebFosters/project-camp#10]
done seeding database using php artisan db:seed, im using windows 10, xampp.

login using the admin account, i can't seem to view or add data from employees upto settings...
currency table is not empty but it doesn't display
![image](https://user-images.githubusercontent.com/4970710/66693520-4967a400-ecdc-11e9-91fc-ab7f69c02937.png)
![image](https://user-images.githubusercontent.com/4970710/66693529-5d130a80-ecdc-11e9-80cf-b252d1ba452b.png)

and when i add data it just keeps on loading.
![image](https://user-images.githubusercontent.com/4970710/66693549-ab280e00-ecdc-11e9-8dbc-d1033e693002.png)

adding new ticket and expense doesn''t pop-up.

**Comment by kwaknet01** [comment]
so xampp is using mariadb? does this compatible with laravel env database configuration?

```
'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'unix_socket' => env('DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'strict' => false,
            'engine' => null,
        ],
```

```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=database name
DB_USERNAME=root
DB_PASSWORD=
```

**Comment by twf-nikhila** [comment]
Hello @kwaknet01 

It should work with any MySQL or MariaDB. Check demo it works.

Something problem in your system environment.
