### ISSUE TITLE
The Mix manifest does not exist

### ISSUE THREAD

**Issue by yserrata** [TheWebFosters/project-camp#12]
Any Solution for this???

i Tried everything....

PHP 7.*

ErrorException thrown with message "The Mix manifest does not exist. (View: C:\xampp\htdocs\project-camp\resources\views\layouts\admin.blade.php)"

Stacktrace:
#65 ErrorException in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php:603
#64 Illuminate\View\Engines\CompilerEngine:handleViewException in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:45
#63 Exception in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php:603
#62 mix in C:\xampp\htdocs\project-camp\storage\framework\views\6a1a74b504d4db25f6bd613801bd498b199da98d.php:219
#61 include in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:43
#60 Illuminate\View\Engines\PhpEngine:evaluatePath in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php:59
#59 Illuminate\View\Engines\CompilerEngine:get in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\View\View.php:142
#58 Illuminate\View\View:getContents in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\View\View.php:125
#57 Illuminate\View\View:renderContents in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\View\View.php:90
#56 Illuminate\View\View:render in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Http\Response.php:42
#55 Illuminate\Http\Response:setContent in C:\xampp\htdocs\project-camp\vendor\symfony\http-foundation\Response.php:202
#54 Symfony\Component\HttpFoundation\Response:__construct in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Router.php:750
#53 Illuminate\Routing\Router:toResponse in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Router.php:722
#52 Illuminate\Routing\Router:prepareResponse in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Router.php:682
#51 Illuminate\Routing\Router:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#50 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\app\Http\Middleware\CheckEmployee.php:24
#49 App\Http\Middleware\CheckEmployee:handle in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
#48 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#47 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php:41
#46 Illuminate\Routing\Middleware\SubstituteBindings:handle in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
#45 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#44 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php:43
#43 Illuminate\Auth\Middleware\Authenticate:handle in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
#42 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#41 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php:75
#40 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
#39 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#38 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php:49
#37 Illuminate\View\Middleware\ShareErrorsFromSession:handle in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
#36 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#35 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php:63
#34 Illuminate\Session\Middleware\StartSession:handle in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
#33 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#32 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php:37
#31 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
#30 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#29 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php:66
#28 Illuminate\Cookie\Middleware\EncryptCookies:handle in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
#27 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#26 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:104
#25 Illuminate\Pipeline\Pipeline:then in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Router.php:684
#24 Illuminate\Routing\Router:runRouteWithinStack in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Router.php:659
#23 Illuminate\Routing\Router:runRoute in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Router.php:625
#22 Illuminate\Routing\Router:dispatchToRoute in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Router.php:614
#21 Illuminate\Routing\Router:dispatch in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:176
#20 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:30
#19 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\fideloper\proxy\src\TrustProxies.php:57
#18 Fideloper\Proxy\TrustProxies:handle in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
#17 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#16 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:31
#15 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
#14 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#13 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php:31
#12 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
#11 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#10 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php:27
#9 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
#8 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#7 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:62
#6 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:163
#5 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php:53
#4 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php:104
#3 Illuminate\Pipeline\Pipeline:then in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:151
#2 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in C:\xampp\htdocs\project-camp\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:116
#1 Illuminate\Foundation\Http\Kernel:handle in C:\xampp\htdocs\project-camp\public\index.php:55
#0 require_once in C:\xampp\htdocs\project-camp\server.php:21

**Comment by thushgithub** [comment]
Did you try to install npm install?

**Comment by yserrata** [comment]
> Did you try to install npm install?

yes i did

**Comment by thushgithub** [comment]
try those thinks 

npm install
npm run development
npm run production

it will work

**Comment by twf-nikhila** [comment]
Hello @yserrata 

1. Clone the repository.
2. Run
`composer install`
3. Compile asset by running below command:
`npm install;`
`npm production;`
make sure you have nodejs and npm installed before running this command.

4. Copy the .env.example to .env file. Configure the .env file with the app details and database details.
5. Run
`php artisan key:generate`


Everything should work fine now.

Or if you need a better Wordpress like 5 minutes installer without following the steps you can purchase the pro version from [here](https://codecanyon.net/item/projectcamp-powerful-project-management-web-application/24061815).

Thank you

**Comment by yserrata** [comment]
Hi, sorry for the late response
After NPM INSTALL---AND STILL GETThe Mix manifest does not exist message


warn ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
2415 warn img-loader@3.0.1 requires a peer of imagemin@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
2416 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
2417 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
2418 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
2418 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
2418 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
2418 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
2419 verbose stack Error: node-sass@4.11.0 postinstall: `node scripts/build.js`
2419 verbose stack Exit status 1
2419 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
2419 verbose stack     at EventEmitter.emit (events.js:219:5)
2419 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2419 verbose stack     at ChildProcess.emit (events.js:219:5)
2419 verbose stack     at maybeClose (internal/child_process.js:1027:16)
2419 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:5)
2420 verbose pkgid node-sass@4.11.0
2421 verbose cwd C:\xampp\htdocs\project-camp
2422 verbose Windows_NT 10.0.18363
2423 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2424 verbose node v13.3.0
2425 verbose npm  v6.13.1
2426 error code ELIFECYCLE
2427 error errno 1
2428 error node-sass@4.11.0 postinstall: `node scripts/build.js`
2428 error Exit status 1
2429 error Failed at the node-sass@4.11.0 postinstall script.
2429 error This is probably not a problem with npm. There is likely additional logging output above.
2430 verbose exit [ 1, true ]
