### ISSUE TITLE
Support SQLite

### ISSUE THREAD

**Issue by alex-phillips** [TheWebFosters/project-camp#4]
I imagine it would work pretty seamlessly since it's built with laravel, but it looks like the artisan migration fails on sqlite databases.

**Comment by am-chris** [comment]
@alex-phillips I'm working on a PR that makes migrations compatible with SQLite and adds feature tests. Already fixed migrations, just need to add tests.

**Comment by twf-nikhila** [comment]
@alex-phillips  we haven't tested it in sqlite database, mostly using mysql for development.
@am-chris that's really great, Thank you in advance.
