### ISSUE TITLE
help create users. admin, etc

### ISSUE THREAD

**Issue by kwaknet01** [TheWebFosters/project-camp#8]
thank you!

**Comment by am-chris** [comment]
@kwaknet01 Hi. Not sure if you're talking about creating users via 1) the website or 2) the code. 

1) To create employees via the website: go to Employees sidebar link, click Employees then click the New Employee button. The process is the same for creating Customers, just go to the Customers sidebar link.

2) To create users via code: check out database/seeds/UserSeeder.php. This file contains an example of how to create a user with Admin permissions (the Role is called superadmin.) Also check out the database/seeds/PermissionsTableSeeder.php, it shows how to create Roles/Permissions via code.

Hopefully this helps. Thanks!

**Comment by kwaknet01** [comment]
so i've found the command, 'php artisan db:seed' will do the work thanks ! @am-chris
