### ISSUE TITLE
Update to Vuetify 2.x or change it to AdminLTE bootstrap 4 theme?

### ISSUE THREAD

**Issue by twf-nikhila** [TheWebFosters/project-camp#9]
Hey Folks,

As a developer of this project, we're looking for choosing a stable development stack. 

**Backend**: Laravel + MySQL has always worked for us and we will continue using it.

**Frontend**: Currently we're using Vuetify 1.5, but new version 2.x is now available. Updating it from 1.5 to 2.x will need a complete rewrite of many different components or maybe we need to rewrite entire frontend. Now is a good time for us to decide using vuetify or bootstrap based AdminLTE or some other you suggest.

The reason we're looking for AdminLTE is that the interface looks good, based on stable bootstrap framework, flexible design, lots of bootstrap-based available plugins(for example date-range which isn't available for vuetify)

The new design will be available as a pro version with lots of refined interfaces, designs & features.

What are your suggestions? Feel free to share your thoughts and help us navigate to something better.

If you have something personal to suggest you can connect with me on my email nikhila@thewebfosters.com

**Comment by am-chris** [comment]
@twf-nikhila I haven't used AdminLTE so I can't offer much of an educated opinion, but I do like Vuetify's extensive options for components and overall Vue integration. 

Have you considered using stubs for supporting presets? I think if a rewrite is required, we might as well stub the first version of UI, so we can add support more theme/JS options (react, vue, jquery?) at some point pretty easily.

**Comment by twf-nikhila** [comment]
Successfully updated to Vuetify 2
